// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAETpmwsZ6d91ZluSZOSaL8JB5-Q7CcDMY',
    appId: '1:979692880562:web:3efa1cf20b5529b502bfab',
    messagingSenderId: '979692880562',
    projectId: 'final-demo-proj',
    authDomain: 'final-demo-proj.firebaseapp.com',
    databaseURL: 'https://final-demo-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'final-demo-proj.appspot.com',
    measurementId: 'G-CVLLLNLJX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6dfOpj2r-pvyWcFcgM9bG6k7f2g9e58',
    appId: '1:979692880562:android:c340f477c38fb4d802bfab',
    messagingSenderId: '979692880562',
    projectId: 'final-demo-proj',
    databaseURL: 'https://final-demo-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'final-demo-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCgr4R1K-V4PjWNuq14Z6JsvGdDFs0cZY',
    appId: '1:979692880562:ios:7b63760f009fe89402bfab',
    messagingSenderId: '979692880562',
    projectId: 'final-demo-proj',
    databaseURL: 'https://final-demo-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'final-demo-proj.appspot.com',
    iosBundleId: 'com.example.rahhal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCgr4R1K-V4PjWNuq14Z6JsvGdDFs0cZY',
    appId: '1:979692880562:ios:7b63760f009fe89402bfab',
    messagingSenderId: '979692880562',
    projectId: 'final-demo-proj',
    databaseURL: 'https://final-demo-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'final-demo-proj.appspot.com',
    iosBundleId: 'com.example.rahhal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAETpmwsZ6d91ZluSZOSaL8JB5-Q7CcDMY',
    appId: '1:979692880562:web:404d6327db38092502bfab',
    messagingSenderId: '979692880562',
    projectId: 'final-demo-proj',
    authDomain: 'final-demo-proj.firebaseapp.com',
    databaseURL: 'https://final-demo-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'final-demo-proj.appspot.com',
    measurementId: 'G-179TCDWWQL',
  );

}